controller_list:
  - name: fake_braccio_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: fake_braccio_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_joint
initial:  # Define initial robot poses per group
  - group: braccio_arm
    pose: home
  - group: braccio_hand
    pose: close